CC = clang
CFLAGS = -O3 -DNDEBUG -Wall -std=c17
LDFLAGS = -static
all:
	@echo shiori/shiolink
shiori: shiori.c
	$(CC) -o shiori.dll $< $(CFLAGS) $(LDFLAGS) -shared
shiolink: shiolink.c
	$(CC) -o shiori.exe $< $(CFLAGS) $(LDFLAGS)
doc: $(wildcard *.h)
	doxygen
